### ISSUE TITLE
执行.py文件会多输出“>>> ”和"... "4个字符

### ISSUE THREAD

**Issue by 475079076** [luodeb/Starry#4]
执行print语句时输出“>>> ”
可能其他语句输出"... "

**Comment by cairami** [comment]
hongxin写了个python文件，内容是多个print("0123456789")。用/bin/python3.11执行时，每行都会显示>>>  0123456789，感觉像是交互模式而非命令行模式。命令行模式应该把整个块读入后再执行。原因不明，也可能和syscall有关。

这个issue优先级最高。

**Comment by cairami** [comment]
这个issue已经于4月3日fixed了。

原因：python无论是脚本还是交互模式，都会执行_PyRun_AnyFileObject函数做分流判断。_Py_FdIsInteractive函数返回1，进入交互模式；其它值，进入脚本模式。_Py_FdIsInteractive调用isatty(fileno(fp))，isatty调用syscall_ioctl，request参数为TIOCGWINSZ。如果ioctl返回0，isatty就返回1。而starry中TIOCGWINSZ的ioctl总是返回0

修改：我们观察到isatty调用syscall_ioctl时fd为4，所以把fd：4，request：TIOCGWINSZ的ioctl的返回值改为非零值。目前是Ok(-1)；其它fd（0,1,2）依然返回OK(0)。这里不能让所有fd都返回Ok(-1)，否则会导致启动starry后hung住，不能进入到/。

**Comment by cairami** [comment]
运行bin/python3.11 lib/python3.11/test/test_bool.py，返回
..............................
----------------------------------------------------------------------
Ran 30 tests in 1.558s

OK

说明脚本模式运行成功。
